3.2.1: prepare release for 3.2.1
voxpupuli/puppet-augeasproviders_core pull request #43
Opened 2022-12-19 18:32 UTC by b4ldr

release for 3.2.1 which includes two minor bug fixes.

2022-12-21 17:52 UTC, ekohl requested changes
@alexjfisher suggested this before, but please use `Release 3.2.1` as the commit message.

2023-01-03 12:55 UTC, b4ldr commented
updated

2023-01-03 13:27 UTC, ekohl reviewed
Neither change shows up in the resulting module on the forge (since we exclude those files) so I wonder what the point of releasing this is. For comparison, I built both using `rake module:build` (where I was lazy and used git master):
```console
$ diff -Nutr puppet-augeasproviders_core-3.2.0 puppet-augeasproviders_core-3.2.1-rc0
diff -Nutr puppet-augeasproviders_core-3.2.0/metadata.json puppet-augeasproviders_core-3.2.1-rc0/metadata.json
--- puppet-augeasproviders_core-3.2.0/metadata.json	2023-01-03 14:25:35.000000000 +0100
+++ puppet-augeasproviders_core-3.2.1-rc0/metadata.json	2023-01-03 14:24:01.000000000 +0100
@@ -1,6 +1,6 @@
 {
   "name": "puppet-augeasproviders_core",
-  "version": "3.2.0",
+  "version": "3.2.1-rc0",
   "author": "Vox Pupuli",
   "summary": "Alternative Augeas-based providers for Puppet",
   "license": "Apache-2.0",
```

2023-01-03 16:31 UTC, b4ldr commented
@ekohl thanks, the main reason was for #43 but will ping the author of that to get more info

@lollipopman in relation to #43 how did you hit this issue, did you pull in this module from forge or git?  if the later where you using a specific tag or just master?

2023-01-03 17:02 UTC, lollipopman commented
@b4ldr & @ekohl I used g10k to pull the modules directly from github, based on the v3.2.0 tag, which is how I ran into this issue.

2023-01-03 18:06 UTC, b4ldr commented
just noting also that the puppet-posfix library [imports rspec files from the spec dir in this repo](https://github.com/bodgit/puppet-postfix/blob/main/spec/spec_helper_local.rb#L3). This is probably not the best idea but its the reason they are not using the forge module

2023-01-03 20:08 UTC, lollipopman commented
> just noting also that the puppet-posfix library [imports rspec files from the spec dir in this repo](https://github.com/bodgit/puppet-postfix/blob/main/spec/spec_helper_local.rb#L3). This is probably not the best idea but its the reason they are not using the forge module

thanks @b4ldr, here is what the error looks like in CI, https://github.com/lollipopman/puppet-postfix/actions/runs/3832180811/jobs/6522193480#step:5:4355

2023-01-03 22:28 UTC, ekohl commented
That looks like it doesn't include rspec-mocks. Perhaps it's because of https://github.com/lollipopman/puppet-postfix/blob/6fa18a696d86a6014889fd8c04e78a4b4cfb0dfd/spec/spec_helper.rb#L3-L5 which AFAIK disables `rspec-mocks`. I'd suggest to migrate the module to use rspec-mocks.

2023-01-03 22:29 UTC, ekohl commented
Oh, I should also mention that it's because of https://github.com/voxpupuli/puppet-augeasproviders_core/commit/637108ebcdab86b2de29ff51b41dfc6db39ab4d9 where it was changed.

2023-01-03 22:36 UTC, lollipopman commented
> Oh, I should also mention that it's because of [637108e](https://github.com/voxpupuli/puppet-augeasproviders_core/commit/637108ebcdab86b2de29ff51b41dfc6db39ab4d9) where it was changed.

Thanks @ekohl for looking at this, that commit is indeed what broke bodgit/puppet-postfix's test, as I mentioned in my pull request, https://github.com/voxpupuli/puppet-augeasproviders_core/commit/aa427ad6ea03dbec36c95c8d92c668509b2fb1cb

2023-01-06 09:26 UTC, bastelfreak commented
@b4ldr can you please rebase after https://github.com/voxpupuli/puppet-augeasproviders_core/pull/44 was merged?

2023-04-25 21:43 UTC, h-haaks commented
@b4ldr can you please rebase after #49 was merged?
And change your commit message to `Release 3.2.1`

2023-04-26 10:39 UTC, b4ldr commented
> @alexjfisher suggested this before, but please use `Release 3.2.1` as the commit message.

done and rebased

2023-04-26 10:42 UTC, ekohl requested changes
Can you regenerate the changelog too? The date is off and by now we've merged a real change (workaround for augeas 1.13.0 bug).

2023-04-26 17:23 UTC, b4ldr commented
> Can you regenerate the changelog too? The date is off and by now we've merged a real change (workaround for augeas 1.13.0 bug).

updated

2023-04-26 17:34 UTC, ekohl approved these changes
If you regen the changelog one more time that PR should have the correct label. Feel free to release it then.

2023-04-26 17:34 UTC, ekohl commented on CHANGELOG.md
> +- Workaround libaugeas save/load issue [\#49](https://github.com/voxpupuli/puppet-augeasproviders_core/pull/49) ([h-haaks](https://github.com/h-haaks))
I've labeled this as abugfix

2023-04-26 18:19 UTC, b4ldr commented on CHANGELOG.md
> +- Workaround libaugeas save/load issue [\#49](https://github.com/voxpupuli/puppet-augeasproviders_core/pull/49) ([h-haaks](https://github.com/h-haaks))
done

2023-04-26 18:20 UTC, b4ldr commented
updated

2023-04-26 21:01 UTC, merged